FROM python:latest

COPY requirements.txt /code/
COPY setup.py /code/
COPY  ./flascholarly/ /code/flascholarly/

WORKDIR /code/

RUN pip install gunicorn &&\
    pip install -r requirements.txt

WORKDIR /code/flascholarly/

CMD gunicorn --access-logfile - --bind 0.0.0.0:5000 app:app 
