version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        image: nginx:0.1.0
        ports:
            - '80:80'
        networks:
            - webnet
        depends_on:
            - flascholarly
    flascholarly:
        build:
            context: .
            dockerfile: Dockerfile-flascholarly
        image: flascholarly:0.1.0
        networks:
            webnet:
                aliases:
                    - flascholarly
networks:
    webnet:
